spring:
  application:
    name: msclientes
  profiles:
    active: local

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://cursoms-eureka-user:ecok-usr-eeuramssur@${EUREKA-SERVER}:8761/eureka
  instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

managment:
  endpoints:
    web:
      exposure:
        incliude: '*'

loggin:
  file:
    name: ./logs/log-file.log